Repository leveler-dba/leveler, pull requests merged in 2020-04, with the labels that each got.

#69 Adding schema to payment URL if missing
  src/components/SignUp/registration.js
Labels: bug, priority 1

#71 47 resources page
  package.json
  src/assets/icons/leveler.svg
  src/components/Animations/Loading.js
  src/components/App/index.js
  src/components/Firebase/firebase.js
  src/components/Icons/Leveler.js
  src/components/Icons/index.js
  src/components/Resources/ResourceItem.js
  src/components/Resources/index.js
  src/constants/routes.js
  src/index.scss
  src/styles/_resources.scss
  yarn.lock
Labels: component, enhancement

#74 72 check valid venmo paypal links
  src/components/Modal/PaymentInstruction.js
  src/components/Resources/ResourceItem.js
  src/components/SignUp/registration.js
  src/index.scss
  src/styles/_form.scss
  src/styles/_modal.scss
Labels: enhancement

#78 small copy changes
  src/components/Modal/PaymentInstruction.js
Labels: enhancement

#81 47 resources page
  src/components/Resources/ResourceItem.js
  src/components/Resources/index.js
  src/styles/_resources.scss
Labels: component, enhancement

#82 Staging
  package.json
  src/assets/icons/leveler.svg
  src/components/About/index.js
  src/components/Animations/Loading.js
  src/components/App/index.js
  src/components/Distribute/index.js
  src/components/Firebase/firebase.js
  src/components/FooterNav/index.js
  src/components/Home/index.js
  src/components/Icons/Leveler.js
  src/components/Icons/index.js
  src/components/Modal/PaymentInstruction.js
  src/components/Resources/ResourceItem.js
  src/components/Resources/index.js
  src/components/SignUp/index.js
  src/components/SignUp/registration.js
  src/constants/routes.js
  src/index.scss
  src/styles/_form.scss
  src/styles/_home.scss
  src/styles/_modal.scss
  src/styles/_resources.scss
  yarn.lock
Labels: bug, component, enhancement, refactor/cleanup

#86 85 add updates to homepage
  src/components/Distribute/DistributeCard.js
  src/components/Distribute/index.js
  src/components/Firebase/firebase.js
  src/components/Home/index.js
  src/components/Resources/index.js
  src/components/SignUp/registration.js
  src/styles/_home.scss
Labels: enhancement

#87 Staging
  src/components/Distribute/DistributeCard.js
  src/components/Distribute/index.js
  src/components/Firebase/firebase.js
  src/components/Home/index.js
  src/components/Resources/index.js
  src/components/SignUp/registration.js
  src/styles/_home.scss
Labels: enhancement

#89 Staging
  src/components/Distribute/index.js
  src/components/Firebase/firebase.js
  src/components/Home/index.js
  src/components/SignUp/registration.js
Labels: enhancement

#99 distribute card renders locations correctly
  src/components/Distribute/DistributeCard.js
  src/styles/_distribute.scss
Labels: refactor/cleanup

#100 Staging
  src/components/Distribute/DistributeCard.js
  src/components/Home/index.js
Labels: refactor/cleanup

#102 101 ip location lookup
  package.json
  src/components/Distribute/index.js
  yarn.lock
Labels: enhancement

#103 Staging
  package.json
  src/components/Distribute/index.js
  yarn.lock
Labels: enhancement, refactor/cleanup

#104 Staging
  src/components/Distribute/index.js
Labels: bug
