Repository leveler-dba/leveler, pull requests merged in 2020-03, with the labels that each got.

#2 added maintenance message
  src/components/Home/index.js
  src/index.css
Labels: bug

#4 Minor Cleanup, Ready to be take off Maintenance
  src/components/Home/index.js
Labels: enhancement

#13 9 add db components
  package.json
  src/assets/animations/loading.svg
  src/assets/icons/cash.svg
  src/assets/icons/patreon.svg
  src/assets/icons/paypal.svg
  src/assets/icons/venmo.svg
  src/components/Animations/Loading.js
  src/components/Animations/index.js
  src/components/Distribute/DistributeCard.js
  src/components/Distribute/DistributeLink.js
  src/components/Distribute/index.js
  src/components/Firebase/firebase.js
  src/components/Home/index.js
  src/components/Icons/Cash.js
  src/components/Icons/Patreon.js
  src/components/Icons/Paypal.js
  src/components/Icons/Venmo.js
  src/components/Icons/index.js
  src/index.css
  yarn.lock
Labels: enhancement

#14 2.0 development
  README.md
  package.json
  src/assets/animations/loading.svg
  src/assets/icons/cash.svg
  src/assets/icons/patreon.svg
  src/assets/icons/paypal.svg
  src/assets/icons/venmo.svg
  src/components/Animations/Loading.js
  src/components/Animations/index.js
  src/components/App/index.js
  src/components/Distribute/DistributeCard.js
  src/components/Distribute/DistributeLink.js
  src/components/Distribute/index.js
  src/components/Firebase/firebase.js
  src/components/FooterNav/index.js
  src/components/Header/index.js
  src/components/Home/index.js
  src/components/Icons/Cash.js
  src/components/Icons/Patreon.js
  src/components/Icons/Paypal.js
  src/components/Icons/Venmo.js
  src/components/Icons/index.js
  src/components/SignUp/index.js
  src/constants/routes.js
  src/index.css
  yarn.lock
Labels: component, enhancement

#17 15 new card ui
  src/components/Distribute/DistributeCard.js
  src/components/Distribute/DistributeHeader.js
  src/components/Distribute/index.js
  src/components/FooterNav/index.js
  src/index.css
Labels: enhancement

#22 18 total entries count
  src/components/Firebase/firebase.js
  src/components/Home/index.js
Labels: enhancement

#30 29-Migrate About Page
  package.json
  public/manifest.json
  src/components/About/About.md
  src/components/About/index.js
  src/components/App/index.js
  src/components/FooterNav/index.js
  src/constants/routes.js
  src/index.scss
  src/styles/_about.scss
  src/styles/_home.scss
  yarn.lock
Labels: enhancement

#44 38 contribute page
  README.md
  package.json
  src/components/About/About.md
  src/components/About/index.js
  src/components/App/index.js
  src/components/Contribute/index.js
  src/components/Distribute/index.js
  src/components/FooterNav/index.js
  src/components/Header/ContributeBand.js
  src/components/Home/index.js
  src/components/SignUp/index.js
  src/components/Success/index.js
  src/constants/routes.js
  src/styles/_footer.scss
  src/styles/_home.scss
  yarn.lock
Labels: component, enhancement, refactor/cleanup

#45 38 contribute page
  src/components/Contribute/index.js
Labels: enhancement

#46 Staging
  README.md
  package.json
  src/components/About/About.md
  src/components/About/index.js
  src/components/App/index.js
  src/components/Contribute/index.js
  src/components/Distribute/index.js
  src/components/FooterNav/index.js
  src/components/Header/ContributeBand.js
  src/components/Home/index.js
  src/components/SignUp/index.js
  src/components/Success/index.js
  src/constants/routes.js
  src/styles/_footer.scss
  src/styles/_home.scss
  yarn.lock
Labels: component, enhancement, refactor/cleanup

#54 configured eslint
  .eslintrc
  package.json
  yarn.lock
Labels: documentation, enhancement

#56 55 rename ga events
  .eslintrc
  README.md
  package.json
  src/components/About/About.md
  src/components/Distribute/DistributeCard.js
  src/components/Firebase/firebase.js
  src/components/FooterNav/index.js
  src/components/Home/index.js
  yarn.lock
Labels: bug, enhancement

#59 57 add random icon
  src/assets/icons/question_mark.svg
  src/components/Contribute/index.js
  src/components/Distribute/DistributeLink.js
  src/components/Icons/QuestionMark.js
  src/components/Icons/index.js
Labels: bug

#60 added contribute band analytics event
  src/components/FooterNav/index.js
  src/components/Header/ContributeBand.js
Labels: bug, enhancement

#64 Staging
  .eslintrc
  package.json
  src/components/Distribute/DistributeCard.js
  src/components/Firebase/firebase.js
  src/components/FooterNav/index.js
  src/components/Header/ContributeBand.js
  src/components/Home/index.js
Labels: component, enhancement
